# etcd configuration

proxy:
  use: true
  host: 192.168.20.141
  port: 3128

etcd:
  # https://etcd.io/docs/v3.6/install/
  version: v3.6.0

  ca:
    cn: "etcd europe CA"
    csr:
      C: France
      L: Paris
      O: Europe
      ST: Ile de France
    expiry: 43830h
  hostname: 192.168.20.52
  initial_cluster: 192.168.20.52=https://192.168.20.52:2380
